<?php

/**
 * @file
 *
 * @copyright (C) Copyright 2009 Palantir.net
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements Views' hook_views_api().
 */
function feed_fields_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implements Views' hook_views_plugins().
 */
function feed_fields_views_plugins() {
  return array(
    'module' => 'views', // Use Views' core theme functions.
    'row' => array(
      'feed_fields' => array(
        'title' => t('Fields'),
        'help' => t('Render fields as the body of feed items.'),
        'handler' => 'feed_fields_plugin_row_fields_rss',
        'parent' => 'views_plugin_row_fields',
        'theme' => 'views_view_fields', // Overridden in feed_fields_plugin_row_fields_rss::render().
        'uses fields' => TRUE,
        'uses options' => TRUE,
        'type' => 'feed',
      ),
    ),
  );
}
