source 'https://rubygems.org'

gem "compass"

# jekyll-assets plugin itself
gem "jekyll-assets"

# Additional gems for jekyll-assets
gem "uglifier"      # And we want our javascripts to be minified with UglifyJS

