<?php
/**
 * @file
 * Code for the Field Museum blog feature.
 */

include_once 'fmnh_blog.features.inc';

/**
 * Embed the filter menu under the science blog link.
 *
 * @param $variables
 * @param $hook
 */
function fmnh_blog_preprocess_menu_link(&$variables, $hook) {
  if (isset($variables['theme_hook_suggestion']) && 'menu_link__menu_block__main_menu__section' == $variables['theme_hook_suggestion']) {
    $href = $variables['element']['#href'];
    if ('science/blog' == $href) {
      $variables['theme_hook_suggestion'] = 'menu_link__menu_block__main_menu__section__science_blog';
    }
  }
}

/**
 * Implementation of hook_ctools_plugin_directory() to let the system know
 * we implement task and task_handler plugins.
 */
function fmnh_blog_ctools_plugin_directory($module, $plugin) {
  // Most of this module is implemented as an export ui plugin, and the
  // rest is in ctools/includes/ctools_access_ruleset.inc
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/' . $plugin;
  }
}

function fmnh_blog_menu_position_rule_plugins() {
  return array(
    'topic' => array(
      'file' => 'fmnh_blog.menu_position.inc',
    ),
  );
}

/**
 * Implement hook_blog_pathauto_alias_alter().
 */
function fmnh_blog_pathauto_alias_alter(&$alias, array &$context) {
  if ($context['module'] == 'node' && in_array($context['type'], array('blog', 'video', 'podcast'))) {
    $node = $context['data']['node'];
    $items = field_get_items('node', $node, 'field_topic');
    if ($items) {
      foreach ($items as $item) {
        $tids = array();
        $tids[] = $item['target_id'];
        $parents = taxonomy_get_parents_all($item['target_id']);
        foreach ($parents as $parent) {
          $tids[] = $parent->tid;
        }
        if (in_array(901, $tids)) {
          $alias = 'science/'. $alias;
          break;
        }
        else if (in_array(806, $tids)) {
          $alias = 'educators/'. $alias;
          break;
        }
        else if (in_array(1311, $tids)) {
          $alias = 'support/members/'. $alias;
          break;
        }
      }
    }
  }
}
