<?php
/**
 * @file
 * Drupal needs this blank file.
 */
include_once 'fmnh_science_tags.features.inc';

/**
 * @param $entity_type
 * @param $bundle
 */
function fmnh_science_tags_create_field_instances($entity_type, $bundle) {
  $field_instances= array();

  if (!field_info_instance($entity_type, 'field_location_region', $bundle)) {
    // Exported field_instance: 'node-collection-field_location_region'
    $field_instances["$entity_type-$bundle-field_location_region"] = array(
      'bundle' => $bundle,
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'field_formatter_class' => '',
            'link' => 1,
          ),
          'type' => 'entityreference_label',
          'weight' => 6,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => $entity_type,
      'field_name' => 'field_location_region',
      'label' => 'Location/Region',
      'required' => 0,
      'settings' => array(
        'behaviors' => array(
          'taxonomy-index' => array(
            'status' => TRUE,
          ),
        ),
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 57,
      ),
    );
  }

  if (!field_info_instance($entity_type, 'field_research_area', $bundle)) {
    // Exported field_instance: 'node-collection-field_research_area'
    $field_instances["$entity_type-$bundle-field_research_area"] = array(
      'bundle' => $bundle,
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'field_formatter_class' => '',
            'link' => 1,
          ),
          'type' => 'entityreference_label',
          'weight' => 5,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => $entity_type,
      'field_name' => 'field_research_area',
      'label' => 'Research area',
      'required' => 0,
      'settings' => array(
        'behaviors' => array(
          'taxonomy-index' => array(
            'status' => TRUE,
          ),
        ),
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 56,
      ),
    );
  }

  if (!field_info_instance($entity_type, 'field_science_focus', $bundle)) {
    // Exported field_instance: 'node-collection-field_science_focus'
    $field_instances["$entity_type-$bundle-field_science_focus"] = array(
      'bundle' => $bundle,
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'field_formatter_class' => '',
            'link' => 1,
          ),
          'type' => 'entityreference_label',
          'weight' => 3,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => $entity_type,
      'field_name' => 'field_science_focus',
      'label' => 'Science Focus',
      'required' => 0,
      'settings' => array(
        'behaviors' => array(
          'taxonomy-index' => array(
            'status' => TRUE,
          ),
        ),
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 59,
      ),
    );
  }

  if (!field_info_instance($entity_type, 'field_stratigraphy', $bundle)) {
    // Exported field_instance: 'node-collection-field_stratigraphy'
    $field_instances["$entity_type-$bundle-field_stratigraphy"] = array(
      'bundle' => $bundle,
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'field_formatter_class' => '',
            'link' => 1,
          ),
          'type' => 'entityreference_label',
          'weight' => 7,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => $entity_type,
      'field_name' => 'field_stratigraphy',
      'label' => 'Stratigraphy',
      'required' => 0,
      'settings' => array(
        'behaviors' => array(
          'taxonomy-index' => array(
            'status' => TRUE,
          ),
        ),
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => 58,
      ),
    );
  }
  foreach ($field_instances as $instance) {
    field_create_instance($instance);
  }
}

/**
 * @param $entity_type
 * @param $bundle
 */
function fmnh_science_tags_create_field_groups($entity_type, $bundle) {

  if (!field_group_exists('group_location_region', $entity_type, $bundle, 'form')) {
    $field_group = new stdClass();
    $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
    $field_group->api_version = 1;
    $field_group->identifier = "group_location_region|$entity_type|$bundle|form";
    $field_group->group_name = 'group_location_region';
    $field_group->entity_type = $entity_type;
    $field_group->bundle = $bundle;
    $field_group->mode = 'form';
    $field_group->parent_name = 'group_science_tags';
    $field_group->data = array(
      'label' => 'Location/Region',
      'weight' => '56',
      'children' => array(
        0 => 'field_location_region',
      ),
      'format_type' => 'htab',
      'format_settings' => array(
        'formatter' => 'closed',
        'instance_settings' => array(
          'description' => '',
          'classes' => 'group-location-region field-group-htab',
          'required_fields' => 1,
          'id' => '',
        ),
      ),
    );
    $field_group = field_group_unpack($field_group);
    field_group_group_save($field_group);
  }

  if (!field_group_exists('group_research_area', $entity_type, $bundle, 'form')) {
    $field_group = new stdClass();
    $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
    $field_group->api_version = 1;
    $field_group->identifier = "group_research_area|$entity_type|$bundle|form";
    $field_group->group_name = 'group_research_area';
    $field_group->entity_type = $entity_type;
    $field_group->bundle = $bundle;
    $field_group->mode = 'form';
    $field_group->parent_name = 'group_science_tags';
    $field_group->data = array(
      'label' => 'Research area',
      'weight' => '55',
      'children' => array(
        0 => 'field_research_area',
      ),
      'format_type' => 'htab',
      'format_settings' => array(
        'formatter' => 'closed',
        'instance_settings' => array(
          'description' => '',
          'classes' => 'group-research-area field-group-htab',
          'required_fields' => 1,
          'id' => '',
        ),
      ),
    );
    $field_group = field_group_unpack($field_group);
    field_group_group_save($field_group);
  }

  if (!field_group_exists('group_science_focus', $entity_type, $bundle, 'form')) {
    $field_group = new stdClass();
    $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
    $field_group->api_version = 1;
    $field_group->identifier = "group_science_focus|$entity_type|$bundle|form";
    $field_group->group_name = 'group_science_focus';
    $field_group->entity_type = $entity_type;
    $field_group->bundle = $bundle;
    $field_group->mode = 'form';
    $field_group->parent_name = 'group_science_tags';
    $field_group->data = array(
      'label' => 'Science focus',
      'weight' => '58',
      'children' => array(
        0 => 'field_science_focus',
      ),
      'format_type' => 'htab',
      'format_settings' => array(
        'formatter' => 'closed',
        'instance_settings' => array(
          'description' => '',
          'classes' => 'group-science-focus field-group-htab',
          'required_fields' => 1,
          'id' => '',
        ),
      ),
    );
    $field_group = field_group_unpack($field_group);
    field_group_group_save($field_group);
  }

  if (!field_group_exists('group_science_tags', $entity_type, $bundle, 'form')) {
    $field_group = new stdClass();
    $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
    $field_group->api_version = 1;
    $field_group->identifier = "group_science_tags|$entity_type|$bundle|form";
    $field_group->group_name = 'group_science_tags';
    $field_group->entity_type = $entity_type;
    $field_group->bundle = $bundle;
    $field_group->mode = 'form';
    $field_group->parent_name = '';
    $field_group->data = array(
      'label' => 'Science tags',
      'weight' => '55',
      'children' => array(
        0 => 'group_location_region',
        1 => 'group_research_area',
        2 => 'group_science_focus',
        3 => 'group_stratigraphy',
      ),
      'format_type' => 'htabs',
      'format_settings' => array(
        'formatter' => '',
        'instance_settings' => array(
          'classes' => 'group-science-tags field-group-htabs',
        ),
      ),
    );
    $field_group = field_group_unpack($field_group);
    field_group_group_save($field_group);
  }

  if (!field_group_exists('group_stratigraphy', $entity_type, $bundle, 'form')) {
    $field_group = new stdClass();
    $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
    $field_group->api_version = 1;
    $field_group->identifier = "group_stratigraphy|$entity_type|$bundle|form";
    $field_group->group_name = 'group_stratigraphy';
    $field_group->entity_type = $entity_type;
    $field_group->bundle = $bundle;
    $field_group->mode = 'form';
    $field_group->parent_name = 'group_science_tags';
    $field_group->data = array(
      'label' => 'Stratigraphy',
      'weight' => '57',
      'children' => array(
        0 => 'field_stratigraphy',
      ),
      'format_type' => 'htab',
      'format_settings' => array(
        'formatter' => 'closed',
        'instance_settings' => array(
          'description' => '',
          'classes' => 'group-stratigraphy field-group-htab',
          'required_fields' => 1,
          'id' => '',
        ),
      ),
    );
    $field_group = field_group_unpack($field_group);
    field_group_group_save($field_group);
  }
}
