<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function fmnh_viewers_ctools_plugin_api($module, $api) {
  if ($module == 'file_entity' && $api == 'file_type') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function fmnh_viewers_field_formatter_info() {
  return array(
    'x3d' => array(
      'label' => t('x3d'),
      'field types' => array('file'),
    ),
    'qt' => array(
      'label' => t('QuickTime VR'),
      'field types' => array('file'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function fmnh_viewers_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'x3d':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'x3d',
          '#file' => (object) $item,
        );
      }
      break;
    case 'qt':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'qt',
          '#file' => (object) $item,
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_theme().
 */
function fmnh_viewers_theme($existing, $type, $theme, $path) {
  return array(
    'x3d' => array(
      'variables' => array('file' => NULL),
      'file' => 'fmnh_viewers.theme.inc',
    ),
    'qt' => array(
      'variables' => array('file' => NULL),
      'file' => 'fmnh_viewers.theme.inc',
    ),
  );
}
