<?php
/**
 * @file
 * Code for the Collection feature.
 */

include_once 'fmnh_collection.features.inc';

/**
 * Set breadcrumb and active menu for collection nodes.
 *
 * @param $node
 * @param $view_mode
 * @param $langcode
 * @return bool
 */
function fmnh_collection_node_view($node, $view_mode, $langcode) {
  if (!empty($node->nid) && $view_mode == 'full' && node_is_page($node) && $node->type == 'collection') {
    $items = field_get_items('node', $node, 'field_department');
    if ($items) {
      $item = reset($items);
      $dept_node = $item['entity'];

      // Retrieve menu item specified in the rule.
      $menu_item = menu_link_get_preferred('node/'. $dept_node->nid .'/collections');

      // Sanity check: if the menu link doesn't exist abort processing the rule.
      if (!$menu_item) {
        return FALSE;
      }

      // Reset the menu trail that views may have set.
      $original_router_item = menu_get_item();
      if ($original_router_item['page_callback'] == 'views_page') {
        $preferred = &drupal_static('menu_link_get_preferred');
        unset($preferred[$context['path']]);
      }

      // Set the active path for the rule's menu.
      menu_tree_set_path($menu_item['menu_name'], $menu_item['link_path']);

      // Manually set the preferred link for this path so that
      // menu_get_active_trail() returns the proper trail.
      $preferred_links = &drupal_static('menu_link_get_preferred');
      $preferred_links[$_GET['q']][MENU_PREFERRED_LINK] = menu_link_get_preferred($menu_item['link_path']);

      // Remove the menu position router from the end of the trail.
      $active_trail = menu_set_active_trail();
      array_pop($active_trail);
      menu_set_active_trail($active_trail);
    }
  }
}
