<?php
/**
 * @file
 * Module for using Mini Panels as page regions.
 */

/**
 * Implements hook_page_build().
 *
 * @see block_page_build()
 */
function region_panels_mini_page_build(&$page) {
  global $theme;

  // The theme system might not yet be initialized. We need $theme.
  drupal_theme_initialize();

  // Fetch a list of regions for the current theme.
  $all_regions = system_region_list($theme);

  $item = menu_get_item();
  if ($item['path'] != 'admin/structure/block/demo/' . $theme) {
    // Check for empty regions.
    foreach (array_keys($all_regions) as $region) {
      if (!isset($page[$region])) {

        // Check for a Mini Panel named for the region.
        $panel_mini = panels_mini_load($region);
        if (!empty($panel_mini) && empty($panel_mini->disabled)) {
          ctools_include('content');
          ctools_include('context');
          $contexts = array();
          if (module_exists('page_manager') && $current_page = page_manager_get_current_page()) {
            if (!empty($current_page['contexts'])) {
              $contexts = ctools_context_match_required_contexts($panel_mini->requiredcontexts, $current_page['contexts']);
            }
          }
          $block = ctools_content_render('panels_mini', $region, NULL, array(), array(), $contexts);
          $page[$region]['#markup'] = $block->content;
          $page[$region]['#sorted'] = TRUE;
        }
      }
    }
  }
}
