<?php
/**
 * @file
 * Code for the Field Museum blog feature.
 */

include_once 'fmnh_blog.features.inc';

/**
 * Embed the filter menu under the science blog link.
 *
 * @param $variables
 * @param $hook
 */
function fmnh_blog_preprocess_menu_link(&$variables, $hook) {
  if (isset($variables['theme_hook_suggestion']) && 'menu_link__menu_block__main_menu__section' == $variables['theme_hook_suggestion']) {
    $href = $variables['element']['#href'];
    if ('science/blog' == $href) {
      $variables['theme_hook_suggestion'] = 'menu_link__menu_block__main_menu__section__science_blog';
    }
  }
}

/**
 * Implementation of hook_ctools_plugin_directory() to let the system know
 * we implement task and task_handler plugins.
 */
function fmnh_blog_ctools_plugin_directory($module, $plugin) {
  // Most of this module is implemented as an export ui plugin, and the
  // rest is in ctools/includes/ctools_access_ruleset.inc
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/' . $plugin;
  }
}

function fmnh_blog_menu_position_rule_plugins() {
  return array(
    'topic' => array(
      'file' => 'fmnh_blog.menu_position.inc',
    ),
  );
}

function fmnh_blog_page_delivery_callback_alter() {
  if (menu_get_item() === FALSE) {
    return;
  }

  $item = menu_get_item();

  if ($item['path'] == 'science/blog/%') {
    // Set the active path for the rule's menu.
    menu_tree_set_path('main-menu', 'menu-position/31');

    // Manually set the preferred link for this path so that
    // menu_get_active_trail() returns the proper trail.
    $preferred_links = &drupal_static('menu_link_get_preferred');
    $preferred_links[$_GET['q']][MENU_PREFERRED_LINK] = menu_link_get_preferred('menu-position/31');

    // Remove the menu position router from the end of the trail.
    $active_trail = menu_set_active_trail();
    menu_set_active_trail($active_trail);
  }
}
