<?php
/**
 * @file
 * homepage_view.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function homepage_view_views_default_views() {
  $export = array();

  $view = new view();
  $view->name = 'homepage';
  $view->description = 'Homepage views';
  $view->tag = '';
  $view->base_table = 'node';
  $view->human_name = '';
  $view->core = 0;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Defaults */
  $handler = $view->new_display('default', 'Defaults', 'default');
  $handler->display->display_options['title'] = 'Explore science';
  $handler->display->display_options['use_more'] = TRUE;
  $handler->display->display_options['use_more_always'] = TRUE;
  $handler->display->display_options['use_more_text'] = 'View all';
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '5';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* Relationship: Content: Explore Science (field_homepage_explorelearn) */
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['id'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['table'] = 'field_data_field_homepage_explorelearn';
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['field'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['label'] = 'Explore and learn noderefs';
  /* Relationship: Content: Happening Now (field_homepage_happeningnow) */
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['id'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['table'] = 'field_data_field_homepage_happeningnow';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['field'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['label'] = 'Happening now noderefs';
  /* Relationship: Content: News (field_homepage_news) */
  $handler->display->display_options['relationships']['field_homepage_news_nid']['id'] = 'field_homepage_news_nid';
  $handler->display->display_options['relationships']['field_homepage_news_nid']['table'] = 'field_data_field_homepage_news';
  $handler->display->display_options['relationships']['field_homepage_news_nid']['field'] = 'field_homepage_news_nid';
  $handler->display->display_options['relationships']['field_homepage_news_nid']['label'] = 'News noderefs';
  /* Relationship: Content: Upcoming (field_homepage_upcoming) */
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['id'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['table'] = 'field_data_field_homepage_upcoming';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['field'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['label'] = 'Upcoming noderefs';
  /* Field: Field: Image */
  $handler->display->display_options['fields']['entity_id']['id'] = 'entity_id';
  $handler->display->display_options['fields']['entity_id']['table'] = 'field_data_field_image';
  $handler->display->display_options['fields']['entity_id']['field'] = 'field_image';
  $handler->display->display_options['fields']['entity_id']['label'] = '';
  $handler->display->display_options['fields']['entity_id']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['entity_id']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['entity_id']['type'] = 'media_original';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Field: Content: Lede */
  $handler->display->display_options['fields']['entity_id_1']['id'] = 'entity_id_1';
  $handler->display->display_options['fields']['entity_id_1']['table'] = 'field_data_field_lede';
  $handler->display->display_options['fields']['entity_id_1']['field'] = 'field_lede';
  $handler->display->display_options['fields']['entity_id_1']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['entity_id_1']['label'] = '';
  $handler->display->display_options['fields']['entity_id_1']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['ellipsis'] = FALSE;
  /* Contextual filter: Content: Nid */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'node';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'home_page' => 'home_page',
  );

  /* Display: Block: Homepage explore and learn */
  $handler = $view->new_display('block', 'Block: Homepage explore and learn', 'block_1');
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['link_display'] = FALSE;
  $handler->display->display_options['link_display'] = 'page_1';
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: Content: Explore Science (field_homepage_explorelearn) */
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['id'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['table'] = 'field_data_field_homepage_explorelearn';
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['field'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['label'] = 'Explore and learn noderefs';
  $handler->display->display_options['relationships']['field_homepage_explorelearn_nid']['required'] = TRUE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['link_to_node'] = TRUE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['type'] = 'styles_file_square_thumbnail';
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_podcast_image']['id'] = 'field_podcast_image';
  $handler->display->display_options['fields']['field_podcast_image']['table'] = 'field_data_field_podcast_image';
  $handler->display->display_options['fields']['field_podcast_image']['field'] = 'field_podcast_image';
  $handler->display->display_options['fields']['field_podcast_image']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['field_podcast_image']['label'] = '';
  $handler->display->display_options['fields']['field_podcast_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_podcast_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_podcast_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_podcast_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_podcast_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_podcast_image']['type'] = 'styles_file_square_thumbnail';
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_photo_gallery_image']['id'] = 'field_photo_gallery_image';
  $handler->display->display_options['fields']['field_photo_gallery_image']['table'] = 'field_data_field_photo_gallery_image';
  $handler->display->display_options['fields']['field_photo_gallery_image']['field'] = 'field_photo_gallery_image';
  $handler->display->display_options['fields']['field_photo_gallery_image']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['field_photo_gallery_image']['label'] = '';
  $handler->display->display_options['fields']['field_photo_gallery_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_photo_gallery_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_photo_gallery_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_photo_gallery_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_photo_gallery_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_photo_gallery_image']['type'] = 'styles_file_square_thumbnail';
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_exhibit_image']['id'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['table'] = 'field_data_field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['field'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['field_exhibit_image']['label'] = '';
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_exhibit_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_exhibit_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_exhibit_image']['type'] = 'styles_file_square_thumbnail';
  /* Field: Content: Thumbnail Image */
  $handler->display->display_options['fields']['field_thumbnail_image']['id'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['table'] = 'field_data_field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['field'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['field_thumbnail_image']['label'] = '';
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_thumbnail_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_thumbnail_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_thumbnail_image']['type'] = 'styles_file_square_thumbnail';
  /* Field: Content: Thumbnail Image */
  $handler->display->display_options['fields']['field_video_thumbnail_image']['id'] = 'field_video_thumbnail_image';
  $handler->display->display_options['fields']['field_video_thumbnail_image']['table'] = 'field_data_field_video_thumbnail_image';
  $handler->display->display_options['fields']['field_video_thumbnail_image']['field'] = 'field_video_thumbnail_image';
  $handler->display->display_options['fields']['field_video_thumbnail_image']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['field_video_thumbnail_image']['label'] = '';
  $handler->display->display_options['fields']['field_video_thumbnail_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_video_thumbnail_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_video_thumbnail_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_video_thumbnail_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_video_thumbnail_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_video_thumbnail_image']['type'] = 'styles_file_square_thumbnail';
  /* Field: Content: Header Image */
  $handler->display->display_options['fields']['field_header_image']['id'] = 'field_header_image';
  $handler->display->display_options['fields']['field_header_image']['table'] = 'field_data_field_header_image';
  $handler->display->display_options['fields']['field_header_image']['field'] = 'field_header_image';
  $handler->display->display_options['fields']['field_header_image']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['field_header_image']['label'] = '';
  $handler->display->display_options['fields']['field_header_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_header_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_header_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_header_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_header_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_header_image']['type'] = 'styles_file_square_thumbnail';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Field: Content: Lede */
  $handler->display->display_options['fields']['entity_id_1']['id'] = 'entity_id_1';
  $handler->display->display_options['fields']['entity_id_1']['table'] = 'field_data_field_lede';
  $handler->display->display_options['fields']['entity_id_1']['field'] = 'field_lede';
  $handler->display->display_options['fields']['entity_id_1']['relationship'] = 'field_homepage_explorelearn_nid';
  $handler->display->display_options['fields']['entity_id_1']['label'] = '';
  $handler->display->display_options['fields']['entity_id_1']['alter']['max_length'] = '190';
  $handler->display->display_options['fields']['entity_id_1']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['trim'] = TRUE;

  /* Display: Block: Homepage news */
  $handler = $view->new_display('block', 'Block: Homepage news', 'block_2');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'News';
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['link_display'] = FALSE;
  $handler->display->display_options['link_display'] = 'page_2';
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: Content: News (field_homepage_news) */
  $handler->display->display_options['relationships']['field_homepage_news_nid']['id'] = 'field_homepage_news_nid';
  $handler->display->display_options['relationships']['field_homepage_news_nid']['table'] = 'field_data_field_homepage_news';
  $handler->display->display_options['relationships']['field_homepage_news_nid']['field'] = 'field_homepage_news_nid';
  $handler->display->display_options['relationships']['field_homepage_news_nid']['label'] = 'News noderefs';
  $handler->display->display_options['relationships']['field_homepage_news_nid']['required'] = TRUE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['relationship'] = 'field_homepage_news_nid';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;

  /* Display: Block: Homepage happening now */
  $handler = $view->new_display('block', 'Block: Homepage happening now', 'block_3');
  $handler->display->display_options['defaults']['link_display'] = FALSE;
  $handler->display->display_options['link_display'] = 'page_3';
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'jcarousel';
  $handler->display->display_options['style_options']['wrap'] = 'circular';
  $handler->display->display_options['style_options']['skin'] = '';
  $handler->display->display_options['style_options']['visible'] = '3';
  $handler->display->display_options['style_options']['scroll'] = '1';
  $handler->display->display_options['style_options']['auto'] = '0';
  $handler->display->display_options['style_options']['autoPause'] = 1;
  $handler->display->display_options['style_options']['easing'] = '';
  $handler->display->display_options['style_options']['vertical'] = 0;
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: Content: Happening Now (field_homepage_happeningnow) */
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['id'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['table'] = 'field_data_field_homepage_happeningnow';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['field'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['label'] = 'Happening now noderefs';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['required'] = TRUE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['link_to_node'] = TRUE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_exhibit_image']['id'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['table'] = 'field_data_field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['field'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['field_exhibit_image']['label'] = '';
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_exhibit_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_exhibit_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_exhibit_image']['type'] = 'styles_file_content-third-home';
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['type'] = 'styles_file_content-third-home';
  /* Field: Content: Thumbnail Image */
  $handler->display->display_options['fields']['field_thumbnail_image']['id'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['table'] = 'field_data_field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['field'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['field_thumbnail_image']['label'] = '';
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_thumbnail_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_thumbnail_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_thumbnail_image']['type'] = 'styles_file_content-third-home';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Field: Content: Lede */
  $handler->display->display_options['fields']['entity_id_1']['id'] = 'entity_id_1';
  $handler->display->display_options['fields']['entity_id_1']['table'] = 'field_data_field_lede';
  $handler->display->display_options['fields']['entity_id_1']['field'] = 'field_lede';
  $handler->display->display_options['fields']['entity_id_1']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['entity_id_1']['label'] = '';
  $handler->display->display_options['fields']['entity_id_1']['alter']['max_length'] = '80';
  $handler->display->display_options['fields']['entity_id_1']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['trim'] = TRUE;

  /* Display: Block: Homepage coming soon */
  $handler = $view->new_display('block', 'Block: Homepage coming soon', 'block_4');
  $handler->display->display_options['defaults']['link_display'] = FALSE;
  $handler->display->display_options['link_display'] = 'page_4';
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'jcarousel';
  $handler->display->display_options['style_options']['wrap'] = 'circular';
  $handler->display->display_options['style_options']['skin'] = '';
  $handler->display->display_options['style_options']['visible'] = '3';
  $handler->display->display_options['style_options']['scroll'] = '1';
  $handler->display->display_options['style_options']['auto'] = '0';
  $handler->display->display_options['style_options']['easing'] = '';
  $handler->display->display_options['style_options']['vertical'] = 0;
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: Content: Upcoming (field_homepage_upcoming) */
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['id'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['table'] = 'field_data_field_homepage_upcoming';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['field'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['label'] = 'Upcoming noderefs';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['required'] = TRUE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['link_to_node'] = TRUE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['type'] = 'styles_file_content-third-home';
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_exhibit_image']['id'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['table'] = 'field_data_field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['field'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['field_exhibit_image']['label'] = '';
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_exhibit_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_exhibit_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_exhibit_image']['type'] = 'styles_file_content-third-home';
  /* Field: Content: Thumbnail Image */
  $handler->display->display_options['fields']['field_thumbnail_image']['id'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['table'] = 'field_data_field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['field'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['field_thumbnail_image']['label'] = '';
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_thumbnail_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_thumbnail_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_thumbnail_image']['type'] = 'styles_file_content-third-home';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Field: Content: Lede */
  $handler->display->display_options['fields']['entity_id_1']['id'] = 'entity_id_1';
  $handler->display->display_options['fields']['entity_id_1']['table'] = 'field_data_field_lede';
  $handler->display->display_options['fields']['entity_id_1']['field'] = 'field_lede';
  $handler->display->display_options['fields']['entity_id_1']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['entity_id_1']['label'] = '';
  $handler->display->display_options['fields']['entity_id_1']['alter']['max_length'] = '80';
  $handler->display->display_options['fields']['entity_id_1']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['trim'] = TRUE;

  /* Display: Page: Homepage happening now */
  $handler = $view->new_display('page', 'Page: Homepage happening now', 'page_3');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'Happening now';
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = TRUE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['use_more_text'] = 'View all';
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: Content: Happening Now (field_homepage_happeningnow) */
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['id'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['table'] = 'field_data_field_homepage_happeningnow';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['field'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['relationships']['field_homepage_happeningnow_nid']['label'] = 'Happening now noderefs';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['link_to_node'] = TRUE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_exhibit_image']['id'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['table'] = 'field_data_field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['field'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['field_exhibit_image']['label'] = '';
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_exhibit_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_exhibit_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_exhibit_image']['type'] = 'styles_file_content-third';
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['type'] = 'styles_file_content-third';
  /* Field: Content: Thumbnail Image */
  $handler->display->display_options['fields']['field_thumbnail_image']['id'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['table'] = 'field_data_field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['field'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['field_thumbnail_image']['label'] = '';
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_thumbnail_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_thumbnail_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_thumbnail_image']['type'] = 'styles_file_content-third';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Field: Content: Lede */
  $handler->display->display_options['fields']['entity_id_1']['id'] = 'entity_id_1';
  $handler->display->display_options['fields']['entity_id_1']['table'] = 'field_data_field_lede';
  $handler->display->display_options['fields']['entity_id_1']['field'] = 'field_lede';
  $handler->display->display_options['fields']['entity_id_1']['relationship'] = 'field_homepage_happeningnow_nid';
  $handler->display->display_options['fields']['entity_id_1']['label'] = '';
  $handler->display->display_options['fields']['entity_id_1']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['path'] = 'homepage/happening-now';

  /* Display: Page: Homepage coming soon */
  $handler = $view->new_display('page', 'Page: Homepage coming soon', 'page_4');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'Coming soon';
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = TRUE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['use_more_text'] = 'View all';
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: Content: Upcoming (field_homepage_upcoming) */
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['id'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['table'] = 'field_data_field_homepage_upcoming';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['field'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['relationships']['field_homepage_upcoming_nid']['label'] = 'Upcoming noderefs';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['link_to_node'] = TRUE;
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_exhibit_image']['id'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['table'] = 'field_data_field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['field'] = 'field_exhibit_image';
  $handler->display->display_options['fields']['field_exhibit_image']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['field_exhibit_image']['label'] = '';
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_exhibit_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_exhibit_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_exhibit_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_exhibit_image']['type'] = 'styles_file_content-third';
  /* Field: Content: Image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['type'] = 'styles_file_content-third';
  /* Field: Content: Thumbnail Image */
  $handler->display->display_options['fields']['field_thumbnail_image']['id'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['table'] = 'field_data_field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['field'] = 'field_thumbnail_image';
  $handler->display->display_options['fields']['field_thumbnail_image']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['field_thumbnail_image']['label'] = '';
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['alter']['path'] = 'node/[nid]';
  $handler->display->display_options['fields']['field_thumbnail_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_thumbnail_image']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_thumbnail_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_thumbnail_image']['type'] = 'styles_file_content-third';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Field: Content: Lede */
  $handler->display->display_options['fields']['entity_id_1']['id'] = 'entity_id_1';
  $handler->display->display_options['fields']['entity_id_1']['table'] = 'field_data_field_lede';
  $handler->display->display_options['fields']['entity_id_1']['field'] = 'field_lede';
  $handler->display->display_options['fields']['entity_id_1']['relationship'] = 'field_homepage_upcoming_nid';
  $handler->display->display_options['fields']['entity_id_1']['label'] = '';
  $handler->display->display_options['fields']['entity_id_1']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['entity_id_1']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['path'] = 'homepage/coming-soon';
  $export['homepage'] = $view;

  return $export;
}
