<?php
// $Id$

/**
 * Implements hook_menu().
 */
function block_export_menu() {
  $items['block/rehash'] = array(
    'page callback' => 'block_export_blocks_rehash',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function block_export_admin_menu_output_alter(&$content) {
  $content['icon']['icon']['flush-cache']['blocks'] = array(
    '#title' => t('Blocks'),
    '#href' => 'block/rehash',
    '#options' => array(
      'query' => drupal_get_destination(),
    ),
  );
}

/**
 * Administration menu callback; flush the class registry cache.
 */
function block_export_blocks_rehash() {
  block_export_rehash();
  drupal_set_message('Blocks rehashed and loaded from code.');
  drupal_goto();
}

/**
 * Implements hook_hook_info().
 */
function block_export_hook_info() {
  $hooks = array(
    'block_info',
    'block_info_alter',
    'block_list_alter',
    'block_configure',
    'block_save',
    'block_view',
    'block_view_alter',
  );

  $hooks = array_combine($hooks, $hooks);
  foreach ($hooks as $hook => $info) {
    $hooks[$hook] = array('group' => 'block');
  }
  return $hooks;
}

function block_export_get_block_info() {
  $info = _block_rehash();
  foreach ($info as $key => &$block) {
    $block['roles'] = db_query("SELECT rid FROM {block_role} WHERE module = :module AND delta = :delta", array(':module' => $block['module'], ':delta' => $block['delta']))->fetchCol();
    $block['node_types'] = db_query("SELECT type FROM {block_node_type} WHERE module = :module AND delta = :delta", array(':module' => $block['module'], ':delta' => $block['delta']))->fetchCol();
    if ($block['module'] == 'block') {
      $block += db_query("SELECT body, info, format FROM {block_custom} WHERE bid = :bid", array(':bid' => $block['delta']))->fetchAssoc();
    }
  }
}

/**
 * Implements hook_flush_caches().
 */
function block_export_flush_caches() {
  block_export_rehash();
}

function block_export_rehash() {
  $blocks = _block_rehash(variable_get('theme_default', 'bartik'));

  foreach ($blocks as $block) {
    $module_info = module_invoke($block['module'], 'block_info');
    $block = $module_info[$block['delta']] + $block;

    if (!empty($block['bid'])) {
      drupal_write_record('block', $block, array('bid'));
    }

    // Because Drupal keeps separate records for each block/theme combination,
    // but only loads certain properties like page visibility settings, etc
    // based on the first result, we have to make sure and update all records.
    db_update('block')
      ->fields(array(
        'visibility' => $block['visibility'],
        'pages' => $block['pages'],
        'custom' => $block['custom'],
        'title' => $block['title'],
      ))
      ->condition('module', $block['module'])
      ->condition('delta', $block['delta'])
      ->execute();

    // Import node type configuration.
    if (isset($block['node_types'])) {
      db_delete('block_node_type')
        ->condition('module', $block['module'])
        ->condition('delta', $block['delta'])
        ->execute();
      foreach ($block['node_types'] as $node_type) {
        db_insert('block_node_type')
          ->fields(array(
            'module' => $block['module'],
            'delta' => $block['delta'],
            'type' => $node_type,
          ))
          ->execute();
      }
    }

    // Import role configuration.
    if (isset($block['roles'])) {
      db_delete('block_role')
        ->condition('module', $block['module'])
        ->condition('delta', $block['delta'])
        ->execute();
      foreach ($block['roles'] as $rid) {
        db_insert('block_role')
          ->fields(array(
            'module' => $block['module'],
            'delta' => $block['delta'],
            'rid' => $rid,
          ))
          ->execute();
      }
    }

    // Import custom configuration.
    //$block['custom_info'] = array();
    if ($block['module'] == 'block' && isset($block['custom_info']) && !empty($block['bid'])) {
      if ($existing_info = db_query("SELECT body, info, format FROM {block_custom} WHERE bid = :bid", array(':bid' => $block['delta']))->fetchAssoc()) {
        $block['custom_info'] += $existing_info;
      }
      $block['custom_info']['bid'] = $block['delta'];
      $block['custom_info'] += array('info' => $block['info']);
      db_merge('block_custom')
        ->fields($block['custom_info'])
        ->key(array('bid' => (int) $block['delta']))
        ->execute();
    }

    if (module_exists('a11y_titles')) {
      $a11y_title_blocks = variable_get('a11y_titles_blocks', array());
      if (isset($block['a11y_title'])) {
        $a11y_title_blocks["{$block['module']}--{$block['delta']}"] = $block['a11y_title'];
      }
      variable_set('a11y_titles_blocks', $a11y_title_blocks);
    }
  }
}
