<?php
/**
 * @file
 * Code for the Field Museum staff feature.
 */

include_once 'fmnh_staff.features.inc';

/**
 *
 */
function fmnh_staff_admin_paths() {
  return array(
    'profile-main/*/edit' => TRUE,
  );
}

function fmnh_staff_navbar_alter(&$items) {
  $items['user']['tray']['user_links']['#links']['main-profile'] = array(
    'title' => t('My public staff profile'),
    'href' => 'profile-main',
  );
}
