<?php
/**
 * @file
 * fmnh_staff.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function fmnh_staff_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "entitylist" && $api == "entitylist_lists") {
    return array("version" => "1");
  }
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function fmnh_staff_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_default_profile2_type().
 */
function fmnh_staff_default_profile2_type() {
  $items = array();
  $items['main'] = entity_import('profile2_type', '{
    "userCategory" : false,
    "userView" : false,
    "type" : "main",
    "label" : "Main profile",
    "weight" : "0",
    "data" : {
      "registration" : 1,
      "roles" : { "2" : "2", "4" : "4", "5" : "5", "6" : "6", "3" : "3" },
      "use_page" : 1
    },
    "rdf_mapping" : []
  }');
  return $items;
}
