<?php

/**
 * Implement hook_init().
 */
function fmnh_analytics_init() {
  drupal_add_library('fmnh_analytics', 'analytics', TRUE);
}

/**
 * Implement hook_library().
 */
function fmnh_analytics_library() {
  $libraries['analytics'] = array(
    'title' => 'FMNH Analytics',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'fmnh_analytics') . '/js/ga-custom.js' => array(),
//      drupal_get_path('module', 'fmnh_analytics') . '/js/ga-custom-events.js' => array(),
//      drupal_get_path('module', 'fmnh_analytics') . '/js/ga-custom-scroll.js' => array(),
//      drupal_get_path('module', 'fmnh_analytics') . '/js/ga-disqus-callbacks.js' => array(),
    ),
  );
  return $libraries;
}

/**
 * @param $entity
 * @param $type
 * @param $view_mode
 * @param $langcode
 */
function fmnh_analytics_entity_view($entity, $type, $view_mode, $langcode) {

  // Decorate social sharing links on nodes.
  if (isset($entity->content['links']['sharing'])) {
    foreach ($entity->content['links']['sharing']['#links'] as $id => &$link) {
      $link['attributes']['data-analytics'] = substr($id, 5) .'-share';
    }
  }
}
