<?php
/**
 * @file
 * faq_content_type.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function faq_content_type_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_faq_long_question'
  $field_bases['field_faq_long_question'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_faq_long_question',
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 1,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_sortorder'
  $field_bases['field_sortorder'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_sortorder',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        -20 => -20,
        -19 => -19,
        -18 => -18,
        -17 => -17,
        -16 => -16,
        -15 => -15,
        -14 => -14,
        -13 => -13,
        -12 => -12,
        -11 => -11,
        -10 => -10,
        -9 => -9,
        -8 => -8,
        -7 => -7,
        -6 => -6,
        -5 => -5,
        -4 => -4,
        -3 => -3,
        -2 => -2,
        -1 => -1,
        0 => 0,
        1 => 1,
        2 => 2,
        3 => 3,
        4 => 4,
        5 => 5,
        6 => 6,
        7 => 7,
        8 => 8,
        9 => 9,
        10 => 10,
        11 => 11,
        12 => 12,
        13 => 13,
        14 => 14,
        15 => 15,
        16 => 16,
        17 => 17,
        18 => 18,
        19 => 19,
        20 => 20,
      ),
      'allowed_values_function' => '',
      'allowed_values_php' => '',
    ),
    'translatable' => 1,
    'type' => 'list_integer',
  );

  return $field_bases;
}
