<?php
/**
 * @file
 * Code for the Field Museum staff feature.
 */

include_once 'fmnh_staff.features.inc';

/**
 *
 */
function fmnh_staff_admin_paths() {
  return array(
    'profile-main/*/edit' => TRUE,
  );
}

function fmnh_staff_navbar_alter(&$items) {
  $items['user']['tray']['user_links']['#links']['main-profile'] = array(
    'title' => t('My public staff profile'),
    'href' => 'profile-main',
  );
}

/**
 * Replace missing profile images with the user's default.
 *
 * @param $variables
 * @param $hook
 */
function fmnh_staff_preprocess_entity(&$variables, $hook) {
  if ($variables['entity_type'] == 'profile2') {
    list($id, $vid, $bundle) = entity_extract_ids('profile2', $variables['profile2']);
    if ($bundle == 'main') {
      $items = field_get_items('profile2', $variables['profile2'], 'field_image');
      if (!$items) {
        $account = user_load($variables['elements']['#entity']->uid);
        $variables['content']['field_image'] = array(
          '#theme' => 'user_picture',
          '#account' => $account,
        );
      }
    }
  }
}
